### ISSUE TITLE
Can you re-upload 1.10.2 version please

### ISSUE THREAD

**Issue by b0bst3r** [Minecolonies/minecolonies#117]
### Minecolonies version
minecolonies-universal-1.10.2-0.4.762
Forge 12.18.1.2075
### Expected behavior
Expected it to load
### Actual behaviour
It doesn't Forge says jar/zip is corrupt
### Steps to reproduce the problem
[18:51:42] [Client thread/WARN]: Zip file minecolonies-universal-1.10.2-0.4.762.jar failed to read properly, it will be ignored
java.lang.NullPointerException
	at net.minecraftforge.fml.common.MetadataCollection.parseModMetadataList(MetadataCollection.java:96) ~[MetadataCollection.class:?]
	at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:79) ~[MetadataCollection.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:57) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:381) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:520) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:216) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[18:51:42] [Client thread/WARN]: ****************************************

**Comment by Kostronor** [comment]
Thanks for the report!

It seems our build system is having problems with the new versions... I'll reupload a hopefully fixed version.

**Comment by Kostronor** [comment]
We have some problems building our jar files, we have to wait for the ForgeGradle team to help us out check MinecraftForge/ForgeGradle#385 for updates

**Comment by TheXWolf** [comment]
Have you tried building in eclipse? When I run the command manually I'd get that a lot, but through eclipse I never get those anymore.

**Comment by Kostronor** [comment]
The thing is, our build system does not work. If you can produce a temporary jar, feel free to on the 1.10.2 branch and send it to me.
