### ISSUE TITLE
crash when loading

### ISSUE THREAD

**Issue by scigeotech** [Minecolonies/minecolonies#137]
### Minecolonies version
0.4.4.3
### Expected behavior
to actually load
### Actual behaviour
crashes
### Steps to reproduce the problem
load mc

> ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/17/16 8:44 PM
Description: Initializing game

java.lang.NoSuchFieldError: textureWidth
	at com.minecolonies.client.model.ModelEntityCitizenFemaleCitizen.<init>(ModelEntityCitizenFemaleCitizen.java:20)
	at com.minecolonies.client.render.RenderBipedCitizen.<clinit>(RenderBipedCitizen.java:20)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:76)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:69)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:212)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:504)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.minecolonies.client.model.ModelEntityCitizenFemaleCitizen.<init>(ModelEntityCitizenFemaleCitizen.java:20)
	at com.minecolonies.client.render.RenderBipedCitizen.<clinit>(RenderBipedCitizen.java:20)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:76)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:69)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:212)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:504)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 65338472 bytes (62 MB) / 344641536 bytes (328 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2079 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2079.jar) 
	UCH	Forge{12.18.1.2079} [Minecraft Forge] (forge-1.10.2-12.18.1.2079.jar) 
	UCH	cordage{1.0.1} [Cordage] (cordage-1.0.1.jar) 
	UCH	csaddle{1.2} [Craftable Saddles] (Craftable Saddles 1.2.jar) 
	UCH	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCH	ExplosivGuns{1.0.0} [ExplosivGuns] (Explosiv'Guns 1.0.0.jar) 
	UCH	samsfooddetails{1.0.1} [Food Details] (FoodDetails-1.10.2-1.0.1.jar) 
	UCH	JEI{3.9.4.254} [Just Enough Items] (jei_1.10.2-3.9.4.254.jar) 
	UCH	minecolonies{1.10.2-0.4.821} [MineColonies] (minecolonies-universal-1.10.2-0.4.821.jar) 
	UCH	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.10.2-forge1.10.2-12.18.1.2079
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4331, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Occupied.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz

**Comment by Raycoms** [comment]
There might be some problem with the other mods.
Are you using any design, render, shader mod?

**Comment by BlackSilent** [comment]
I've the same crash with only the mod and the latest forge (.2088 to .2091)
Perhaps the problem is with the version on curse, on the site and the launcher it says 0.4.4.3 but when dowload it, I got 0.4.825?

**Comment by Raycoms** [comment]
It's super strange because we didn't change anything in these classes and
models.
Could you try some older versions of forge? 2079?

2016-09-17 23:47 GMT-03:00 BlackSilent <notifications@github.com>:

**Comment by BlackSilent** [comment]
nope, same crash

**Comment by Raycoms** [comment]
Can you try it with this jar:

https://www.dropbox.com/sh/9cnqcjl0nan57cy/AABpzKW4AOflZZfLUZP09SWRa/branch/feature/%2357-Update-to-1.10.2/minecolonies-universal-1.10.2-0.4.821.jar?dl=0

(Maybe the jar on curse has been corrupted)

2016-09-17 23:58 GMT-03:00 BlackSilent <notifications@github.com>:

**Comment by BlackSilent** [comment]
didn't change anything

**Comment by Raycoms** [comment]
Did some updates: does this fix it? (even on smp) ?

https://www.dropbox.com/sh/9cnqcjl0nan57cy/AADkb7Ss-465Y_j7Ro3Dj104a/branch/feature/%2357-Update-to-1.10.2/minecolonies-universal-1.10.2-0.4.822.jar?dl=0

2016-09-18 0:05 GMT-03:00 BlackSilent <notifications@github.com>:

**Comment by Raycoms** [comment]
If yes I'll upload this on curse.


2016-09-18 0:22 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by BlackSilent** [comment]
sorry, but no, still the same bug

**Comment by scigeotech** [comment]
yo its some rendering bug
