### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#152]
### Minecolonies version

v828

Profiling our server with only one player online, this comes out:

```
[19:46:31] [Lag Spike Detector/ERROR] [TickProfiler/]: The server appears to have lag spiked.
Last tick 0.22234762s ago."Server thread" RUNNABLE
    at com.minecolonies.colony.Colony.onServerTick(Colony.java:445)
    at com.minecolonies.colony.ColonyManager.onServerTick(ColonyManager.java:408)
    at com.minecolonies.event.FMLEventHandler.onServerTick(FMLEventHandler.java:23)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_FMLEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)


[19:48:01] [Lag Spike Detector/ERROR] [TickProfiler/]: The server appears to have lag spiked.
Last tick 0.20206869s ago."Server thread" RUNNABLE
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:450)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:131)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:104)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:68)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115)
    at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132)
    at net.minecraft.world.World.func_72964_e(World.java:303)
    at net.minecraft.world.World.func_175726_f(World.java:298)
    at net.minecraft.world.World.func_175625_s(World.java:106)
    at com.minecolonies.colony.Colony.cleanUpBuildings(Colony.java:790)
    at com.minecolonies.colony.Colony.onWorldTick(Colony.java:720)
    at com.minecolonies.colony.ColonyManager.lambda$onWorldTick$58(ColonyManager.java:509)
    at com.minecolonies.colony.ColonyManager$$Lambda$621/997447693.accept(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.minecolonies.colony.ColonyManager.onWorldTick(ColonyManager.java:509)
    at com.minecolonies.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:47)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:130)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

```

These may be false positives but it should be checked if there is something wrong with it. I think we are doing too much work on the server (having over 50 colonies atm)

**Comment by Kostronor** [comment]
we fixed these
