### ISSUE TITLE
Odd issue with builder

### ISSUE THREAD

**Issue by xannor** [Minecolonies/minecolonies#234]
I think there might be a mod conflict with Railcraft. If I hire a builder my server console and logs get flooded with an error line.
console:
[Server thread/WARN] [minecolonies/]: Action for target com.minecolonies.entity.ai.util.AITarget@2ff71016 threw an exception:
java.lang.ClassCastException

logs additionally show:
[Server thread/ERROR] [minecolonies/]: Invalid tool crowbar not implemented as tool!
### Minecolonies version

1.10.2: 0.4.7.11 
### Expected behavior

No errors.
### Actual behaviour

This error repeated as long as a builder is hired, firing the builder makes the error go away.
### Steps to reproduce the problem

Install railcraft?

In addition there are no jobs queued for the builder. I also would see this on the miner and I attributed it to my being impatient and attempting to fast build the mineshaft. I had to keep breaking stairs as the miner would get stuck, once I broke stairs where he wanted to place a cobble platform he would continue. This same error would get logged during that issue as well. I cannot figure out how to work around the builder having this problem and it is preventing me from trying out the guard towers. The builder will just stand in their hut while this is logging.

**Comment by Oggal** [comment]
this is an issue with RailcRaft rails, The effective tool is Crowbar and crowbar is not added as tool. handing the citizen a crowbar is a workaround but a proper solution is needed.

**Comment by xannor** [comment]
Thanks for the suggestion, ill try it, but I am not sure it is just rails. I don't think the builder was trying to target any rails nearby (they are not close) and the miner seems to get this same issue if there are ladder bits below its expected digging level (when digging the shaft.) I will try giving them a crowbar when they next get stuck and let you know what results I get.

**Comment by Kostronor** [comment]
Well the problem seems to be with the `crowbar ` tool that is not implementing all tool things it (and we) need.

Can you send a forge log for when this happens?

**Comment by xannor** [comment]
here is the log where the builder started with its errors.

https://gist.github.com/xannor/dbc711ecfb586a4be23bdbd5d161218d

It also contains the messages when the miner was stuck with the same message, I would have to remove ladders to fix him.

I also encounterd another error today with the builder and upgrading a citizen 4 to 5, do you want it included here or as a separate issue?

**Comment by Kostronor** [comment]
```
[21:52:34] [Server thread/WARN] [minecolonies/]: Action for target com.minecolonies.entity.ai.util.AITarget@2ff71016 threw an exception:
java.lang.ClassCastException: com.minecolonies.colony.buildings.BuildingBuilder cannot be cast to com.minecolonies.colony.buildings.BuildingFisherman
	at com.minecolonies.entity.ai.citizen.fisherman.EntityAIWorkFisherman.getOwnBuilding(EntityAIWorkFisherman.java:252) ~[EntityAIWorkFisherman.class:?]
	at com.minecolonies.entity.ai.citizen.fisherman.EntityAIWorkFisherman.getOwnBuilding(EntityAIWorkFisherman.java:43) ~[EntityAIWorkFisherman.class:?]
	at com.minecolonies.entity.ai.basic.AbstractEntityAIBasic.initSafetyChecks(AbstractEntityAIBasic.java:230) ~[AbstractEntityAIBasic.class:?]
	at com.minecolonies.entity.ai.util.AITarget.apply(AITarget.java:125) ~[AITarget.class:?]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:191) ~[AbstractAISkeleton.class:?]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:174) ~[AbstractAISkeleton.class:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) [?:1.8.0_72]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) [?:1.8.0_72]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) [?:1.8.0_72]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) [?:1.8.0_72]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) [?:1.8.0_72]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_72]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) [?:1.8.0_72]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) [?:1.8.0_72]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_72]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) [?:1.8.0_72]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128) [AbstractAISkeleton.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [tr.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773) [sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2189) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [sg.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155) [rt.class:?]
	at com.minecolonies.entity.EntityCitizen.func_70636_d(EntityCitizen.java:695) [EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [sg.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1964) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1750) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

Seems like the builder thinks he is a fisherman. Can you try firing and rehiring him?

And yes, separate issue please.

**Comment by xannor** [comment]
I have since then and I could build the guard towers. I had moved my fisherman to the builder job as the level was much higher. (fishermen seem to gain levels much faster than others.). That error is most likely similar to https://github.com/Minecolonies/minecolonies/issues/109.

**Comment by Raycoms** [comment]
Does this still happen?

**Comment by marvin-bitterlich** [comment]
closing es inactive for now
