### ISSUE TITLE
Can not get Sound and Crash

### ISSUE THREAD

**Issue by sventx** [Minecolonies/minecolonies#280]
### Minecolonies version

minecolonies-universal-1.10.2-0.4.1719.jar

### Expected behavior

- The builder can create a building :)

### Actual behaviour

- Crashing while playing a sound :(

### Steps to reproduce the problem

1. Create a Colony
2. Start a new Buildung
3. The Builder want to remove something
4. Crash, see Log
[crash-2016-11-13_09.15.34-server.txt](https://github.com/Minecolonies/minecolonies/files/587646/crash-2016-11-13_09.15.34-server.txt)

The easist way to fix is, at a try catch around the sound at com.minecolonies.entity.EntityCitizen.hitBlockWithToolInHand(EntityCitizen.java:1386) ;)

**Comment by Kostronor** [comment]
@sventx Thanks a lot for the bug report! 

@Raycoms seems like something clientOnly:

```
java.lang.NoSuchMethodError: net.minecraft.block.Block.getSoundType(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/entity/Entity;)Lnet/minecraft/block/SoundType;
	at com.minecolonies.entity.EntityCitizen.hitBlockWithToolInHand(EntityCitizen.java:1386)
	at com.minecolonies.entity.EntityCitizen.hitBlockWithToolInHand(EntityCitizen.java:1331)
	at com.minecolonies.entity.ai.basic.AbstractEntityAIBasic.waitingForSomething(AbstractEntityAIBasic.java:299)
	at com.minecolonies.entity.ai.util.AITarget.test(AITarget.java:114)
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:164)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2190)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at com.minecolonies.entity.EntityCitizen.func_70636_d(EntityCitizen.java:747)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sventx** [comment]
Hey,
you are doing an awesome job.
When i use your MineColony Test package (via Curse) it not crashed.
If i use it in a vanilla Forge Minecraft it crashed. Is their some interdependence?

Bye

**Comment by Kostronor** [comment]
It could be you are using a different forge version? What version are you using?

**Comment by sventx** [comment]
Hey,
see the logfile ;)

```-- System Details --
Details:
...
	FML: MCP 9.32 Powered by Forge 12.18.1.2018 14 mods loaded, 14 mods active```

**Comment by Kostronor** [comment]
Can you try it with Forge 2099? Thats the recommended one for now and it should fix it.

**Comment by sventx** [comment]
Hey,
now it's working. Thank you very much.
