### ISSUE TITLE
Game Crashes when Builder uses shovel

### ISSUE THREAD

**Issue by Gelantine** [Minecolonies/minecolonies#297]
### Minecolonies version

version 0.4.1776 or curse X.X.XX

### Expected behavior

- XXX

### Actual behaviour

- Game Crashes

### Steps to reproduce the problem

1. Tell builder to build building
2. He needs a shovel
3. give him shovel
4. in the moment he starts using it the game crashes

I've got several other mods installed (from crash report)
UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2007-1.10.0.jar) 
	UCHIJAAAA	Forge{12.18.0.2007} [Minecraft Forge] (forge-1.10.2-12.18.0.2007-1.10.0.jar) 
	UCHIJAAAA	counter_guns{1.0.1} [Counter Guns] (CounterGuns-1.10.2-1.0.1.jar) 
	UCHIJAAAA	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.9-1.10.2.jar) 
	UCHIJAAAA	JEI{3.7.7.233} [Just Enough Items] (Just-Enough-Items-Mod-1.10.2.jar) 
	UCHIJAAAA	KaishiWeapons{v0.1} [Kaishi's Weapons Pack] (KaishiWeapons-1.9.4.jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.4.1776} [MineColonies] (minecolonies-universal-1.10.2-0.4.1776.jar) 
	UCHIJAAAA	mfs{4.0.0} [Minecraft Flight Simulator] (Minecraft Flight Simulator-1.10.2-4.0.0(1).jar) 
	UCHIJAAAA	parachutemod{1.5.2} [Parachute Mod] (parachutemod-ng-1.10.2-1.5.2-409.jar) 
	UCHIJAAAA	treechopper{1.0.3a} [Tree Chopper] (TreeChopper-1.0.3a.jar) 
	UCHIJAAAA	vc{v2.9.7a-mc1.10.2} [ViesCraft] (ViesCraft-2.9.7a-mc1.10.2.jar) 
	UCHIJAAAA	XaeroMinimap{1.10} [Xaero's Minimap] (Xaeros_Minimap_1.10_Forge_1.10.2.jar)

**Comment by Raycoms** [comment]
Could you send us the complete crash report?

2016-11-22 8:50 GMT-02:00 Gelantine <notifications@github.com>:

**Comment by Gelantine** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 22.11.16 20:01
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.block.Block.getSoundType(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/entity/Entity;)Lnet/minecraft/block/SoundType;
	at com.minecolonies.entity.EntityCitizen.hitBlockWithToolInHand(EntityCitizen.java:1386)
	at com.minecolonies.entity.EntityCitizen.hitBlockWithToolInHand(EntityCitizen.java:1331)
	at com.minecolonies.entity.ai.basic.AbstractEntityAIBasic.waitingForSomething(AbstractEntityAIBasic.java:299)
	at com.minecolonies.entity.ai.basic.AbstractEntityAIBasic$$Lambda$72/546898690.getAsBoolean(Unknown Source)
	at com.minecolonies.entity.ai.util.AITarget.test(AITarget.java:114)
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:164)
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton$$Lambda$111/987028568.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:900)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2189)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:685)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at com.minecolonies.entity.EntityCitizen.func_70636_d(EntityCitizen.java:747)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.entity.EntityCitizen.hitBlockWithToolInHand(EntityCitizen.java:1386)
	at com.minecolonies.entity.EntityCitizen.hitBlockWithToolInHand(EntityCitizen.java:1331)
	at com.minecolonies.entity.ai.basic.AbstractEntityAIBasic.waitingForSomething(AbstractEntityAIBasic.java:299)
	at com.minecolonies.entity.ai.basic.AbstractEntityAIBasic$$Lambda$72/546898690.getAsBoolean(Unknown Source)
	at com.minecolonies.entity.ai.util.AITarget.test(AITarget.java:114)
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:164)
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton$$Lambda$111/987028568.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:900)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2189)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:685)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at com.minecolonies.entity.EntityCitizen.func_70636_d(EntityCitizen.java:747)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Entity being ticked --
Details:
	Entity Type: minecolonies.Citizen (com.minecolonies.entity.EntityCitizen)
	Entity ID: 14376
	Entity Name: Steven Z. Allen
	Entity's Exact location: -3007,54, 4,00, -1048,44
	Entity's Block location: World: (-3008,4,-1049), Chunk: (at 0,0,7 in -188,-66; contains blocks -3008,0,-1056 to -2993,255,-1041), Region: (-6,-3; contains chunks -192,-96 to -161,-65, blocks -3072,0,-1536 to -2561,255,-1025)
	Entity's Momentum: 0,10, -0,08, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: New World_Tests
	All players: 1 total; [EntityPlayerMP['Gelantine'/184, l='New World_Tests', x=-3014,63, y=4,00, z=-1052,11]]
	Chunk stats: ServerChunkCache: 881 Drop: 0
	Level seed: 2508220168991906513
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,2*minecraft:dirt,minecraft:grass;1;village
	Level spawn location: World: (-603,4,-1561), Chunk: (at 5,0,7 in -38,-98; contains blocks -608,0,-1568 to -593,255,-1553), Region: (-2,-4; contains chunks -64,-128 to -33,-97, blocks -1024,0,-2048 to -513,255,-1537)
	Level time: 441084 game time, 53 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 68345 (now: false), thunder time: 106999 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 313334064 bytes (298 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.0.2007 Optifine OptiFine_1.10.2_HD_U_C3 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2007-1.10.0.jar) 
	UCHIJAAAA	Forge{12.18.0.2007} [Minecraft Forge] (forge-1.10.2-12.18.0.2007-1.10.0.jar) 
	UCHIJAAAA	counter_guns{1.0.1} [Counter Guns] (CounterGuns-1.10.2-1.0.1.jar) 
	UCHIJAAAA	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.9-1.10.2.jar) 
	UCHIJAAAA	JEI{3.7.7.233} [Just Enough Items] (Just-Enough-Items-Mod-1.10.2.jar) 
	UCHIJAAAA	KaishiWeapons{v0.1} [Kaishi's Weapons Pack] (KaishiWeapons-1.9.4.jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.4.1776} [MineColonies] (minecolonies-universal-1.10.2-0.4.1776.jar) 
	UCHIJAAAA	mfs{4.0.0} [Minecraft Flight Simulator] (Minecraft Flight Simulator-1.10.2-4.0.0(1).jar) 
	UCHIJAAAA	parachutemod{1.5.2} [Parachute Mod] (parachutemod-ng-1.10.2-1.5.2-409.jar) 
	UCHIJAAAA	treechopper{1.0.3a} [Tree Chopper] (TreeChopper-1.0.3a.jar) 
	UCHIJAAAA	vc{v2.9.7a-mc1.10.2} [ViesCraft] (ViesCraft-2.9.7a-mc1.10.2.jar) 
	UCHIJAAAA	XaeroMinimap{1.10} [Xaero's Minimap] (Xaeros_Minimap_1.10_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Gelantine'/184, l='New World_Tests', x=-3014,63, y=4,00, z=-1052,11]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.141 High.zip
	OpenGlVersion: 4.5.0 NVIDIA 353.62
	OpenGlRenderer: GeForce GTX 750/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Raycoms** [comment]
Are you playing this on a server? and are you using any sound mods?

2016-11-22 8:50 GMT-02:00 Gelantine <notifications@github.com>:

**Comment by Kostronor** [comment]
You use a sound mod on a dedicated server it seems...

**Comment by Gelantine** [comment]
I'm not Playing on a srever and I didn't install any sound mod (at least I don't know, could be part of another mod..)

**Comment by Kostronor** [comment]
@Gelantine then maybe you have to use a newer version of forge? Try 2099 or 2151, 2007 is a bit old
