### ISSUE TITLE
Server Crash [Unknown]

### ISSUE THREAD

**Issue by Kostronor** [Minecolonies/minecolonies#86]
### Minecolonies version
v472
### Crashlog

```
[21:40:04] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
at net.minecraftforge.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:132) ~[ByteBufUtils.class:?]
at com.minecolonies.colony.workorders.AbstractWorkOrder.serializeViewNetworkD
ata(AbstractWorkOrder.java:313) ~[AbstractWorkOrder.class:?]
at com.minecolonies.network.messages.ColonyViewWorkOrderMessage.(ColonyViewWorkOrderMessage.java:42) ~[ColonyViewWorkOrderMessage.class:?]
at com.minecolonies.colony.Colony.lambda$sendWorkOrderPackets$9(Colony.java:560) ~[Colony.class:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_92]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_92]
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548) ~[?:1.8.0_92]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_92]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_92]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_92]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_92]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_92]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_92]
at com.minecolonies.colony.Colony.sendWorkOrderPackets(Colony.java:560) ~[Colony.class:?]
at com.minecolonies.colony.Colony.updateSubscribers(Colony.java:485) ~[Colony.class:?]
at com.minecolonies.colony.Colony.onServerTick(Colony.java:359) ~[Colony.class:?]
at com.minecolonies.colony.ColonyManager.onServerTick(ColonyManager.java:385) ~[ColonyManager.class:?]
at com.minecolonies.event.FMLEventHandler.onServerTick(FMLEventHandler.java:22) ~[FMLEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_45_FMLEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:253) ~[FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:649) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

@Minecolonies/developers Anyone has an idea what causes this?

**Comment by Raycoms** [comment]
My fisherman will come with a fix for that one =D

2016-09-02 17:23 GMT-03:00 Marvin Hofmann <notifications@github.com>:

**Comment by Kostronor** [comment]
You mean farmer?

**Comment by Raycoms** [comment]
Yeah starts with f as well =D

2016-09-02 17:25 GMT-03:00 Marvin Hofmann <notifications@github.com>:

**Comment by Raycoms** [comment]
I fixed this issue with the recent hotfix.
